device: 'cpu'

batch_size: 5
learning_rate: 1e-3
num_epochs: 100
gradient_clip_val: 1.0

loss_alpha:
  alpha_content: 1e-3
  alpha_style: 1e-5
  alpha_structure: 1e-4
  alpha_ca: 1e-4

optimizer:      # Adam as default
  lr: 1e-4
  weight_decay: 1e-6
  
# Image parameters
Image:
  default_size: 128
  default_channels: 3

  tissue_mask_params: 
    kernel_size: 20
    sigma: 20
    downsample: 8
    background_gray_threshold: 220

  patch_extraction_params:
    patch_size: 128
    patch_tissue_threshold: 0.7
    is_visualize: False